// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCcryNRaiTlaij-FwI1ooIe6-wBQB26zvY',
    appId: '1:114297040367:web:53af6b9cb9a80f3adfda1a',
    messagingSenderId: '114297040367',
    projectId: 'student-manager-4edaa',
    authDomain: 'student-manager-4edaa.firebaseapp.com',
    storageBucket: 'student-manager-4edaa.firebasestorage.app',
    measurementId: 'G-TNDM9M0MC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUpxnKdiCcvZnGZGlYyFowbo8owiepfk0',
    appId: '1:114297040367:android:71457af12f515b58dfda1a',
    messagingSenderId: '114297040367',
    projectId: 'student-manager-4edaa',
    storageBucket: 'student-manager-4edaa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy4Mq7SZxTV5VlMl_S5o2FQQxJhK7Qqas',
    appId: '1:114297040367:ios:813ca8b3ba6999a3dfda1a',
    messagingSenderId: '114297040367',
    projectId: 'student-manager-4edaa',
    storageBucket: 'student-manager-4edaa.firebasestorage.app',
    iosBundleId: 'com.badawi.smartStudent',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy4Mq7SZxTV5VlMl_S5o2FQQxJhK7Qqas',
    appId: '1:114297040367:ios:813ca8b3ba6999a3dfda1a',
    messagingSenderId: '114297040367',
    projectId: 'student-manager-4edaa',
    storageBucket: 'student-manager-4edaa.firebasestorage.app',
    iosBundleId: 'com.badawi.smartStudent',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCcryNRaiTlaij-FwI1ooIe6-wBQB26zvY',
    appId: '1:114297040367:web:25a1409638e7782fdfda1a',
    messagingSenderId: '114297040367',
    projectId: 'student-manager-4edaa',
    authDomain: 'student-manager-4edaa.firebaseapp.com',
    storageBucket: 'student-manager-4edaa.firebasestorage.app',
    measurementId: 'G-0L1FCKT6TE',
  );

}